import cv2
import numpy as np
import pygame
import time
from matplotlib import pyplot as plt
im = cv2.imread("D:/Works/pothole-detection-source-code-master (1)/index4.jpg")
gray1 = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
cv2.imwrite('D:/Works/pothole-detection-source-code-master (1)/graypothholeresult.jpg', gray1)
imgray = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(imgray,127,255,0)
contours1, _ = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
contours2, _ = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
img2 = im.copy()
out = cv2.drawContours(img2, contours2, -1, (250,250,250),1)
cv2.imshow('img1',img2)
cv2.waitKey(0)
plt.subplot(331),plt.imshow(im),plt.title('GRAY')
plt.xticks([]), plt.yticks([])
img = cv2.imread("D:/Works/pothole-detection-source-code-master (1)/index4.jpg",0)
blur = cv2.blur(im,(5,5))
gblur = cv2.GaussianBlur(im,(5,5),0)
median = cv2.medianBlur(im,5)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(median,kernel,iterations = 1)
dilation = cv2.dilate(erosion,kernel,iterations = 5)
closing = cv2.morphologyEx(dilation, cv2.MORPH_CLOSE, kernel)
edges = cv2.Canny(dilation,9,420) 
ret1,threshold=cv2.threshold(edges.copy(),0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
contours,_=cv2.findContours(threshold,cv2.RETR_LIST,cv2.CHAIN_APPROX_NONE)
cv2.drawContours(img,contours,-1,(0,0,255),2)
cv2.imshow("Show",img) 
cnt = contours[0]
k = cv2.isContourConvex(cnt)
M = cv2.moments(cnt)
perimeter = cv2.arcLength(cnt,True)
area = cv2.contourArea(cnt)
epsilon = 0.1*cv2.arcLength(cnt,True)
approx = cv2.approxPolyDP(cnt,epsilon,True)
for c in contours:
    rect = cv2.boundingRect(c)
    if rect[2] < 100 or rect[3] < 100: continue
    x,y,w,h = rect
    cv2.rectangle(img2,(x,y),(x+w,y+h),(0,255,0),8)
    cv2.putText(img2,'Moth Detected',(x+w+40,y+h),0,2.0,(0,255,0))
cv2.imshow("Show",img)
plt.subplot(332),plt.imshow(blur),plt.title('BLURRED')
plt.xticks([]), plt.yticks([])
plt.subplot(333),plt.imshow(gblur),plt.title('guassianblur')
plt.xticks([]), plt.yticks([])        
plt.subplot(334),plt.imshow(median),plt.title('Medianblur')
plt.xticks([]), plt.yticks([]) 
plt.subplot(337),plt.imshow(img,cmap = 'gray')
plt.title('dilated Image'), plt.xticks([]), plt.yticks([])
plt.subplot(338),plt.imshow(edges,cmap = 'gray')
plt.title('Edge Image'), plt.xticks([]), plt.yticks([])
plt.subplot(335),plt.imshow(erosion),plt.title('EROSION')
plt.xticks([]), plt.yticks([])
plt.show()
pygame.init()
pygame.mixer.music.load("D:/Works/pothole-detection-source-code-master (1)/buzz.mp3")
pygame.mixer.music.play()
time.sleep(5)